# Default initial positions for mojia's ros2_control fake system

initial_positions:
  right_elbow_pitch_joint: 0
  right_elbow_yaw_joint: 0
  right_shoulder_pitch_joint: 0
  right_shoulder_roll_joint: 0
  right_shoulder_yaw_joint: 0