# ros2_control 控制器配置文件
controller_manager:
  ros__parameters:
    update_rate: 100  # 控制器更新频率，单位Hz

    x1_controller:
      type: joint_trajectory_controller/JointTrajectoryController  # 右臂轨迹控制器

    left_controller:
      type: joint_trajectory_controller/JointTrajectoryController  # 左臂轨迹控制器

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster  # 关节状态广播器

x1_controller:
  ros__parameters:
    joints:
      - right_shoulder_pitch_joint  # 右肩俯仰关节
      - right_shoulder_roll_joint   # 右肩滚转关节
      - right_shoulder_yaw_joint    # 右肩偏航关节
      - right_elbow_pitch_joint     # 右肘俯仰关节
      - right_elbow_yaw_joint       # 右肘偏航关节
      - right_wrist_pitch_joint     # 右腕俯仰关节
    command_interfaces:
      - position    # 控制接口，使用位置模式
    state_interfaces:
      - position    # 状态接口，反馈关节位置
      - velocity    # 状态接口，反馈关节速度

left_controller:
  ros__parameters:
    joints:
      - left_shoulder_pitch_joint   # 左肩俯仰关节
      - left_shoulder_roll_joint    # 左肩滚转关节
      - left_shoulder_yaw_joint     # 左肩偏航关节
      - left_elbow_pitch_joint      # 左肘俯仰关节
      - left_elbow_yaw_joint        # 左肘偏航关节
      - left_wrist_pitch_joint      # 左腕俯仰关节
    command_interfaces:
      - position    # 控制接口，使用位置模式
    state_interfaces:
      - position    # 状态接口，反馈关节位置
      - velocity    # 状态接口，反馈关节速度
