# 运动学相关配置，指定该规划组的运动学解算器及其参数
manipulator:
  # 指定使用的运动学插件，这里使用KDL插件
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  # 运动学求解时的搜索分辨率，数值越小，精度越高但计算更慢
  kinematics_solver_search_resolution: 0.0050000000000000001
  # 运动学求解超时时间（秒），超过该时间则判定失败
  kinematics_solver_timeout: 0.50000000000000001