# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - left_arm_controller
    - right_arm

  left_arm_controller:
    type: FollowJointTrajectory
    joints:
      - left_shoulder_pitch_joint
      - left_shoulder_roll_joint
      - left_shoulder_yaw_joint
      - left_elbow_pitch_joint
      - left_elbow_yaw_joint
      - left_wrist_pitch_joint
    action_ns: follow_joint_trajectory
    default: true
  right_arm:
    type: FollowJointTrajectory
    joints:
      - right_shoulder_pitch_joint
      - right_shoulder_roll_joint
      - right_shoulder_yaw_joint
      - right_elbow_pitch_joint
      - right_elbow_yaw_joint
      - right_wrist_pitch_joint
    action_ns: follow_joint_trajectory
    default: true