# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - x1_controller

  x1_controller:
    type: FollowJointTrajectory
    joints:
      - right_shoulder_pitch_joint
      - right_shoulder_roll_joint
      - right_shoulder_yaw_joint
      - right_elbow_pitch_joint
      - right_elbow_yaw_joint
      - right_wrist_pitch_joint
    action_ns: follow_joint_trajectory
    default: true