# Pilz 轨迹规划器的笛卡尔运动限制参数
cartesian_limits:
  max_trans_vel: 1.0      # 最大平移速度（单位：m/s）
  max_trans_acc: 2.25     # 最大平移加速度（单位：m/s^2）
  max_trans_dec: -5.0     # 最大平移减速度（单位：m/s^2，负值）
  max_rot_vel: 1.57       # 最大旋转速度（单位：rad/s）
